stages:
  - deploy

autodeploy:
  stage: deploy
  before_script:
    - docker stop mattermost-meet-deploy || true &&  docker rm mattermost-meet-deploy || true
  script:
    - docker run -d -p 3001:3000 -w="/home/node/app" -v ./:/home/node/app --name mattermost-meet-deploy node:latest npm install && npm start
  rules:
    - if: '$CI_COMMIT_BRANCH == "ci"'
